#pragma once
#include <iostream>
#include <string>
#include <utility>
#include <vector>
#include <map>
#include <fstream>
#include <iostream>
#include <set>
#include <sstream>
#include <regex>
#include <algorithm>
#include "class/wallet.h"
#include "class/user.h"
#include "class/admin.h"
#include "class/currency.h"
#include "class/dataOperator.h"